server:
  port: 3100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PeterWakeUP/client-my-cofig
          #search-paths: respo1,respo2
          #username: 123
          #password: 123
      #label: master



